all: 
  hosts: {}

  children: 
    dev: 
      hosts:  
        vm-one:
          ansible_user: vagrant
          ansible_host: 192.168.56.10
        vm-two: 
          ansible_user: vagrant 
          ansible_host: 192.168.56.11