# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "machine-two" 
  config.vm.network "private_network", ip: "192.168.56.11"

  config.vm.network "forwarded_port", guest:8080,host:8080
  
  config.vm.provider "virtualbox" do |vb|

  #   # Customize the amount of memory on the VM:
    #vb.cpus=1  # number of CPU core 
    vb.memory = "512" 
  end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y nginx
  SHELL
end
