
# deploy spring service 8080
# mount (image persistence nfs path /mnt/nfs_share)
--- 
- name: Deploy Spring Service 
  hosts: vm-two
  become: true 
  vars: 
    docker_image_name: 69966/springgradleimg:1.1.1

  tasks: 
    - name: Run docker compose 
      community.docker.docker_compose:
        project_name: spring-project
        definition:
          services:   
            spring_service: 
              image: "{{docker_image_name}}"
              container_name: spring_cont
              ports: 
                - "8080:8080"
              volumes: 
                - "/mnt/nfs_share:/app/src/main/resources/images"