---
- name: Setup NFS Server 
  hosts: vm-one
  become: true 

  vars: 
    nfs_export_dir: /srv/nfs/shared
    nfs_client_ip: 192.168.56.11

  tasks: 
    - name: Apt update 
      apt: 
        update_cache: true 
    - name: Install NFS Server Kernel
      apt: 
        name: nfs-kernel-server 
        state: present 
    - name: Create Shared Directory 
      file: 
        path: "{{ nfs_export_dir }}"
        state: directory 
        owner: nobody 
        group: nogroup 
        mode: "0777"
      
    - name: Write Exports Config 
      lineinfile: 
        path: /etc/exports 
        line: "{{ nfs_export_dir}}  {{nfs_client_ip }} (rw,sync,no_subtree_check)"
        create: yes
        state: present 
    - name: Apply configuration 
      command: exportfs -ra
    - name: Restart nfs-server service 
      systemd: 
        name: nfs-kernel-server
        enabled: true 
        state: restarted 