---
- name: Setup NFS Client 
  hosts: nfs-clients 
  become: true 
  vars: 
    nfs_server_ip: 192.168.56.10 
    nfs_remote_dir: /srv/nfs/shared 
    nfs_local_dir: /mnt/nfs_share
  
  tasks: 
  - name: Update Apt 
    apt: 
      update_cache: true 
  - name: Install NFS Client 
    apt: 
      name: nfs-common 
      state: present 
  - name: Create Local Mount Point 
    file: 
      path: "{{nfs_local_dir}}"
      state: directory 
      mode: "0755"
  - name: Mount Remote to local directory 
    mount: 
      src: "{{nfs_server_ip}}:{{nfs_remote_dir}}"
      path: "{{nfs_local_dir}}"
      fstype: nfs 
      opts: defaults,_netdev
      state: mounted 
  - name: Persist mount on reboot 
    mount: 
      src: "{{nfs_server_ip}}:{{nfs_remote_dir}}"
      path: "{{nfs_local_dir}}"
      fstype: nfs 
      opts: defaults,_netdev
      state: present 