---
- name: Install nginx with playbook 
  hosts: dev
  become: true 
  
  tasks: 
    - name: Update apt cache 
      apt: 
        update_cache: yes 
    - name: Install Nginx 
      apt: 
        name: nginx 
        state: present 
    - name: Install neofetch 
      apt: 
        name: neofetch 
        state: present 
    - name: Install Docker 
      apt: 
        name: docker
        state: present 
    - name: Install Docker Compose 
      apt: 
        name: docker-compose 
        state: present 
    - name: Append current user to docker group 
      user:
        name: vagrant
        groups: docker
        append: yes
