---
- name: Run Services inside container 
  hosts: vm-one
  become: true #  sudo 
  tasks: 
    # run nginx container , expose port 3000 
    - name: Run nginx container 
      community.docker.docker_container: 
        name: nginx_container 
        image: nginx:latest 
        ports: 
          - "3000:80"